name: Merge Branches Managed on Issue
description: This actions is responsible for merging listed branches on the specified GitHub issue.
inputs:
  issue-number:
    description: The GitHub issue number in which the branches are listed
    required: true
  path:
    description: Relative path under $GITHUB_WORKSPACE to place the repository
    required: false
  shell:
    description: The shell command to invoke a specified source code. This is typically used for `before-merge` option. The default is `bash -eo pipefail` on Linux. Currently, the Windows platform is not supported. Note this value will be just splitted by whitespaces
    required: false
  before-merge:
    description: Script that will be run before merging through the `shell` option. This will be invoked after checking out to each target and the base branch, so you can modify commits for each branch. This is useful to avoid possible merge conflicts
    required: false
  after-merge:
    description: Script that will be run after merging through the `shell` option. This will be invoked after checking out to each target and the base branch, so you can modify commits for each branch
    required: false
  inputs-param-base-branch:
    description: The name for a base branch in the workflow_dispatch action. The default is "base-branch"
    required: false
  inputs-param-force:
    description: The name for force option in the workflow_dispatch action. The default is "force"
    required: false
  modified-branch-suffix:
    description: The suffix for the modified branch. If you don't set `before-merge` or `after-merge`, the modified branch and the original branch will be the same. The default is ".modified"
    required: false
  comment-prefix:
    description: The comment prefix to trigger some actions. The default is "/mbmi".
    required: false
  token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
branding:
  icon: git-merge
  color: red
outputs:
  diff:
    description: The output of git-diff(1) between the default branch and the head of the merged branch.
  diffstat:
    description: The output of git-diff(1) with `--stat` between the default branch and the head of the merged branch.
runs:
  using: node12
  main: dist/index.js
